# Path to genome file and index
DNA: '/home/ya76/Platinum_Genomes/GENOMES/D.ananassae/DanaPacBio.fa'
INDEX: '/home/ya76/Platinum_Genomes/GENOMES/D.ananassae/index/hisat2'

# Path to basic folders.
OUT_DIR: '/fs/cbsufsrv5/data2/ya76/D_ananassae_Tuxedo_Trinotate_Snakemake'
HOME_DIR: '/home/ya76/GitHub_Repositories/Tuxedo2.Trinotate.PacBio.Snakemake'
WORK_DIR: '/workdir'

# Path to database files and Trinotate home directory.
SHARED_DATABASE: '/shared_data/misc/TRINOTATE_RESOURCES/20160324/'
CUSTOM_DATABASE: '/home/ya76/D.melanogaster/dmel-all-translation-r6.18.fasta'
TRINOTATE_HOME: '/programs/Trinotate-3.0.0'
SQLITE: '/home/ya76/Trinotate/Trinotate.sqlite'

# Path to a JSON file with samples and their corresponding FASTQ files.
PE_SAMPLES_JSON: '/home/ya76/GitHub_Repositories/Tuxedo2.Trinotate.PacBio.Snakemake/samples_pe.json'
SE_SAMPLES_JSON: '/home/ya76/GitHub_Repositories/Tuxedo2.Trinotate.PacBio.Snakemake/samples_se.json'

